// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 23.02.2025, 18:23:11
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/@Front-end/nuxt/nuxt-fake-shop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/plugins/**/*.{js,ts,mjs}","C:/@Front-end/nuxt/nuxt-fake-shop/composables/**/*.{js,ts,mjs}","C:/@Front-end/nuxt/nuxt-fake-shop/utils/**/*.{js,ts,mjs}","C:/@Front-end/nuxt/nuxt-fake-shop/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/@Front-end/nuxt/nuxt-fake-shop/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;