
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {refresh: () => Promise<void>}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'Discount': typeof import("../components/discount/index.vue")['default']
    'LayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LayoutHeaderLink': typeof import("../components/layout/Header/Link.vue")['default']
    'LayoutHeader': typeof import("../components/layout/Header/index.vue")['default']
    'Loader': typeof import("../components/loader/index.vue")['default']
    'MyPagination': typeof import("../components/myPagination/index.vue")['default']
    'ProductContainer': typeof import("../components/product/Container.vue")['default']
    'Product': typeof import("../components/product/index.vue")['default']
    'Search': typeof import("../components/search/index.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'NuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'Icon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'ColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'Checkbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'Input': typeof import("../components/ui/input/index")['Input']
    'PaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'PaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'PaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'PaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'PaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'Pagination': typeof import("../components/ui/pagination/index")['Pagination']
    'PaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'PaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'Button': typeof import("../components/ui/button/index")['Button']
    'Select': typeof import("../components/ui/select/index")['Select']
    'SelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'SelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'SelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'SelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'SelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'SelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'SelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'SelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'SelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'SelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'Skeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyDiscount': typeof import("../components/discount/index.vue")['default']
    'LazyLayoutFooter': typeof import("../components/layout/Footer.vue")['default']
    'LazyLayoutHeaderLink': typeof import("../components/layout/Header/Link.vue")['default']
    'LazyLayoutHeader': typeof import("../components/layout/Header/index.vue")['default']
    'LazyLoader': typeof import("../components/loader/index.vue")['default']
    'LazyMyPagination': typeof import("../components/myPagination/index.vue")['default']
    'LazyProductContainer': typeof import("../components/product/Container.vue")['default']
    'LazyProduct': typeof import("../components/product/index.vue")['default']
    'LazySearch': typeof import("../components/search/index.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtImg': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
    'LazyNuxtPicture': typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
    'LazyIcon': typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
    'LazyColorScheme': typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
    'LazyCheckbox': typeof import("../components/ui/checkbox/index")['Checkbox']
    'LazyInput': typeof import("../components/ui/input/index")['Input']
    'LazyPaginationEllipsis': typeof import("../components/ui/pagination/index")['PaginationEllipsis']
    'LazyPaginationFirst': typeof import("../components/ui/pagination/index")['PaginationFirst']
    'LazyPaginationLast': typeof import("../components/ui/pagination/index")['PaginationLast']
    'LazyPaginationNext': typeof import("../components/ui/pagination/index")['PaginationNext']
    'LazyPaginationPrev': typeof import("../components/ui/pagination/index")['PaginationPrev']
    'LazyPagination': typeof import("../components/ui/pagination/index")['Pagination']
    'LazyPaginationList': typeof import("../components/ui/pagination/index")['PaginationList']
    'LazyPaginationListItem': typeof import("../components/ui/pagination/index")['PaginationListItem']
    'LazyButton': typeof import("../components/ui/button/index")['Button']
    'LazySelect': typeof import("../components/ui/select/index")['Select']
    'LazySelectContent': typeof import("../components/ui/select/index")['SelectContent']
    'LazySelectGroup': typeof import("../components/ui/select/index")['SelectGroup']
    'LazySelectItem': typeof import("../components/ui/select/index")['SelectItem']
    'LazySelectItemText': typeof import("../components/ui/select/index")['SelectItemText']
    'LazySelectLabel': typeof import("../components/ui/select/index")['SelectLabel']
    'LazySelectScrollDownButton': typeof import("../components/ui/select/index")['SelectScrollDownButton']
    'LazySelectScrollUpButton': typeof import("../components/ui/select/index")['SelectScrollUpButton']
    'LazySelectSeparator': typeof import("../components/ui/select/index")['SelectSeparator']
    'LazySelectTrigger': typeof import("../components/ui/select/index")['SelectTrigger']
    'LazySelectValue': typeof import("../components/ui/select/index")['SelectValue']
    'LazySkeleton': typeof import("../components/ui/skeleton/index")['Skeleton']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const Discount: typeof import("../components/discount/index.vue")['default']
export const LayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LayoutHeaderLink: typeof import("../components/layout/Header/Link.vue")['default']
export const LayoutHeader: typeof import("../components/layout/Header/index.vue")['default']
export const Loader: typeof import("../components/loader/index.vue")['default']
export const MyPagination: typeof import("../components/myPagination/index.vue")['default']
export const ProductContainer: typeof import("../components/product/Container.vue")['default']
export const Product: typeof import("../components/product/index.vue")['default']
export const Search: typeof import("../components/search/index.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const NuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const Icon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const ColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const Checkbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const Input: typeof import("../components/ui/input/index")['Input']
export const PaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const PaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const PaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const PaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const PaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const Pagination: typeof import("../components/ui/pagination/index")['Pagination']
export const PaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const PaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const Button: typeof import("../components/ui/button/index")['Button']
export const Select: typeof import("../components/ui/select/index")['Select']
export const SelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const SelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const SelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const SelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const SelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const SelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const SelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const SelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const SelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const SelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const Skeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyDiscount: typeof import("../components/discount/index.vue")['default']
export const LazyLayoutFooter: typeof import("../components/layout/Footer.vue")['default']
export const LazyLayoutHeaderLink: typeof import("../components/layout/Header/Link.vue")['default']
export const LazyLayoutHeader: typeof import("../components/layout/Header/index.vue")['default']
export const LazyLoader: typeof import("../components/loader/index.vue")['default']
export const LazyMyPagination: typeof import("../components/myPagination/index.vue")['default']
export const LazyProductContainer: typeof import("../components/product/Container.vue")['default']
export const LazyProduct: typeof import("../components/product/index.vue")['default']
export const LazySearch: typeof import("../components/search/index.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome.vue")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtImg: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtImg.vue")['default']
export const LazyNuxtPicture: typeof import("../node_modules/@nuxt/image/dist/runtime/components/NuxtPicture.vue")['default']
export const LazyIcon: typeof import("../node_modules/@nuxt/icon/dist/runtime/components/index")['default']
export const LazyColorScheme: typeof import("../node_modules/@nuxtjs/color-mode/dist/runtime/component.vue3.vue")['default']
export const LazyCheckbox: typeof import("../components/ui/checkbox/index")['Checkbox']
export const LazyInput: typeof import("../components/ui/input/index")['Input']
export const LazyPaginationEllipsis: typeof import("../components/ui/pagination/index")['PaginationEllipsis']
export const LazyPaginationFirst: typeof import("../components/ui/pagination/index")['PaginationFirst']
export const LazyPaginationLast: typeof import("../components/ui/pagination/index")['PaginationLast']
export const LazyPaginationNext: typeof import("../components/ui/pagination/index")['PaginationNext']
export const LazyPaginationPrev: typeof import("../components/ui/pagination/index")['PaginationPrev']
export const LazyPagination: typeof import("../components/ui/pagination/index")['Pagination']
export const LazyPaginationList: typeof import("../components/ui/pagination/index")['PaginationList']
export const LazyPaginationListItem: typeof import("../components/ui/pagination/index")['PaginationListItem']
export const LazyButton: typeof import("../components/ui/button/index")['Button']
export const LazySelect: typeof import("../components/ui/select/index")['Select']
export const LazySelectContent: typeof import("../components/ui/select/index")['SelectContent']
export const LazySelectGroup: typeof import("../components/ui/select/index")['SelectGroup']
export const LazySelectItem: typeof import("../components/ui/select/index")['SelectItem']
export const LazySelectItemText: typeof import("../components/ui/select/index")['SelectItemText']
export const LazySelectLabel: typeof import("../components/ui/select/index")['SelectLabel']
export const LazySelectScrollDownButton: typeof import("../components/ui/select/index")['SelectScrollDownButton']
export const LazySelectScrollUpButton: typeof import("../components/ui/select/index")['SelectScrollUpButton']
export const LazySelectSeparator: typeof import("../components/ui/select/index")['SelectSeparator']
export const LazySelectTrigger: typeof import("../components/ui/select/index")['SelectTrigger']
export const LazySelectValue: typeof import("../components/ui/select/index")['SelectValue']
export const LazySkeleton: typeof import("../components/ui/skeleton/index")['Skeleton']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
